CREATE TABLE IF NOT EXISTS PRICE_INFO (
    BRAND_ID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIORITY INT,
    PRICE DECIMAL(10, 2),
    CURRENCY VARCHAR(3),
    PRIMARY KEY (BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID)
);